# Generated by Django 3.1.7 on 2021-02-27 20:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auto_20210227_1508'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='selling_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auctions.user'),
            preserve_default=False,
        ),
    ]
