# Generated by Django 3.1.7 on 2021-02-27 20:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_listing_selling_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='selling_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
